export default {
    NEW_DISCUSSION_SELECT_TOPIC: 'NEW_DISCUSSION_SELECT_TOPIC',
    NEW_DISCUSSION_LEVEL_RANGE_CHANGE: 'NEW_DISCUSSION_LEVEL_RANGE_CHANGE',
    NEW_DISCUSSION_QUESTION_TEXT_CHANGE: 'NEW_DISCUSSION_QUESTION_TEXT_CHANGE',
    NEW_DISCUSSION_NUMBER_OF_DEBATERS_CHANGE: 'NEW_DISCUSSION_NUMBER_OF_DEBATERS_CHANGE',
    NEW_DISCUSSION_TOGGLE_SPECTATORS_ALLOWED: 'NEW_DISCUSSION_TOGGLE_SPECTATORS_ALLOWED',
    NEW_DISCUSSION_CREATED_REQUEST: 'NEW_DISCUSSION_CREATED_REQUEST'
}