export default {
    USER_INITIALIZED: 'USER_INITIALIZED',
    USER_VALUE_CHANGED: 'USER_VALUE_CHANGED',
    USER_TOPIC_CHANGED: 'USER_TOPIC_CHANGED',
    USER_SAVE_CHANGES: "USER_SAVE_CHANGES",
    USER_CANCEL_CHANGES: 'USER_CANCEL_CHANGES'
}